#!/bin/bash
if [ "$#" -ne 3 ]; then  
    echo "Usage: $0 <Species><output><GCF_002485785.1>"  
    exit 1  
fi  
Species=$1
Output=$2
BioSample=$3
datasets  download genome accession $BioSample --include genome --filename $BioSample
unzip -o $BioSample #-o默认覆盖之前的文件
mlst --scheme $Species ./ncbi_dataset/data/$BioSample/*.fna > $Output
cat result
rm -rf $BioSample ./ncbi_dataset

#By：Jacky14
#2025/08/21 00:20